// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/breadcrumb.vue')['default']
    Editor: typeof import('./src/components/markdown/editor.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    HdButton: typeof import('./src/components/form/hd-button.vue')['default']
    HdInput: typeof import('./src/components/form/hd-input.vue')['default']
    HdLink: typeof import('./src/components/form/hd-link.vue')['default']
    Notification: typeof import('./src/components/notification.vue')['default']
  }
}

export { }
